### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by odunybrad** [Orange-OpenSource/cassandra-image#6]
Thanks for providing this useful container. 

I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html) says "Materialized views are considered experimental and are not recommended for production use." And the default value for these two parameters are **False** in the document. They say they will disable them in Cassandra 4.

However, in the latest version of Cassandra (3.11.4), the default value for them are still **True**, as is the setting in your container's cassandra.yaml. 

Shall we disable them manually for now? 
Thanks!

**Comment by cscetbon** [comment]
@hh-project-config yeah you should. That image is designed to be used by [Casskop](https://github.com/Orange-OpenSource/cassandra-k8s-operator) and usually a ConfigMap is used to set only the parameters where non default values are used. We update the default configuration file only when we're aware of changes or during an update to a major version (where changes should happen ...).
